spring.application.name=bank-product-feature-data
#configserver.url=10.121.74.2:10077
configserver.url=localhost:10077
spring.config.import=configserver:http://${configserver.url}
logging.level.brave.Tracer=OFF

server.port=9096

#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@10.121.81.233:1521/ORCL
#spring.datasource.username=srvtadmin
#spring.datasource.password=srvtadmin


